#!/usr/bin/env python3
"""Assemble Code.gs = header + SESSION_RACE_IDS map (from /tmp/session_race_ids.js)
+ the buildSchedule body that emits raceId on each session."""
import sys

HEADER = '''/**
 * MultiGP IO 2026 Schedule API
 *
 * Deploy:
 *   1. Open the sheet → Extensions → Apps Script
 *   2. Paste this whole file in (replace any default Code.gs content)
 *   3. Save (disk icon)
 *   4. Run testBuildSchedule once → grant permissions when prompted →
 *      check the Execution log for sane output
 *   5. Deploy → New deployment → Type: Web app
 *      • Execute as: Me
 *      • Who has access: Anyone
 *      → Copy the /exec URL — that's your API endpoint
 *
 * Endpoints:
 *   GET <url>             → full payload
 *   GET <url>?day=Friday  → sessions filtered to that day
 *
 * Re-deploy after any code change (Manage deployments → edit → New version).
 * Sheet edits are picked up live, no redeploy needed.
 *
 * raceId mapping:
 *   Each session's `raceId` field is looked up from SESSION_RACE_IDS below.
 *   Sessions without a mapping (or no activity) get raceId: null.
 *   To refresh the map after races change on multigp.com, run the matcher:
 *     python3 match_races.py > session_race_ids.js
 *   then paste the new SESSION_RACE_IDS block in here and redeploy.
 */

const EVENT_CONFIG = {
  name: 'MultiGP International Open 2026',
  venue: 'AMA Grounds, Muncie, Indiana',
  timezone: 'America/Indiana/Indianapolis',
  dates: {
    'Wednesday': '2026-06-10',
    'Thursday':  '2026-06-11',
    'Friday':    '2026-06-12',
    'Saturday':  '2026-06-13',
    'Sunday':    '2026-06-14'
  },
  // Leave null to use the first sheet; set to a name to be explicit
  sheetName: null
};

const DAY_NAMES = ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

// ─────────────────────────────────────────────────────────────────────
// Session → multigp.com race ID mapping
// Generated by match_races.py from the live MultiGP chapter race listing.
// Sessions not in this map get raceId: null in the response.
// ─────────────────────────────────────────────────────────────────────

'''

FOOTER = '''
function doGet(e) {
  try {
    const data = buildSchedule();
    const dayParam = e && e.parameter && e.parameter.day;
    if (dayParam) {
      const wanted = dayParam.toLowerCase();
      data.sessions = data.sessions.filter(s => s.day.toLowerCase() === wanted);
    }
    return jsonResponse(data);
  } catch (err) {
    return jsonResponse({ error: err.message, stack: err.stack });
  }
}

function jsonResponse(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function buildSchedule() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = EVENT_CONFIG.sheetName
    ? ss.getSheetByName(EVENT_CONFIG.sheetName)
    : ss.getSheets()[0];
  const values = sheet.getDataRange().getValues();

  const tracksMap = {};   // trackId -> { id, name, location }
  const sessions = [];

  for (let r = 0; r < values.length; r++) {
    const row = values[r];
    // Day-header row has the day name in column D (index 3)
    const headerCell = String(row[3] || '').trim();
    if (!DAY_NAMES.includes(headerCell)) continue;

    const day  = headerCell;
    const date = EVENT_CONFIG.dates[day];

    const locationRow = values[r + 1] || [];
    const trackRow    = values[r + 2] || [];

    // Build column-index → trackId map for this day
    const dayTracks = {};
    for (let c = 1; c < trackRow.length; c++) {
      const trackName = String(trackRow[c] || '').trim();
      const location  = String(locationRow[c] || '').trim();
      if (!trackName || trackName === 'Track Name') continue;
      const id = slug(trackName);
      dayTracks[c] = id;
      if (!tracksMap[id]) {
        tracksMap[id] = { id: id, name: trackName, location: location };
      }
    }

    // Walk time-slot rows until we hit a blank time cell (end of day block)
    for (let sr = r + 3; sr < values.length; sr++) {
      const slotRow = values[sr];
      const timeText = String(slotRow[0] || '').trim();
      if (!timeText) break;

      const range = parseTimeRange(timeText);
      if (!range) continue;

      for (const colIdx in dayTracks) {
        const c = Number(colIdx);
        const trackId = dayTracks[c];
        const cell = String(slotRow[c] || '').trim();
        if (!cell) continue; // empty cell = no scheduled activity, skip

        const isClosed = cell.toLowerCase() === 'closed';
        const id = `${day.toLowerCase()}-${range.start24.replace(':', '')}-${trackId}`;
        sessions.push({
          id: id,
          day: day,
          date: date,
          startTime: range.start24,
          endTime: range.end24,
          trackId: trackId,
          activity: isClosed ? null : cell,
          status: isClosed ? 'closed' : 'scheduled',
          raceId: SESSION_RACE_IDS[id] || null
        });
      }
    }
  }

  return {
    event: EVENT_CONFIG.name,
    venue: EVENT_CONFIG.venue,
    timezone: EVENT_CONFIG.timezone,
    lastUpdated: new Date().toISOString(),
    tracks: Object.values(tracksMap),
    sessions: sessions
  };
}

/**
 * Handles "8 am - 10 am", "10 am - 11 am", "8 pm -9 pm", "9 pm-10 pm",
 * "8:30 am - 9:00 am", etc. Returns { start24, end24 } or null.
 */
function parseTimeRange(text) {
  const norm = text.toLowerCase().replace(/\\s+/g, ' ').trim();
  const re = /(\\d{1,2})(?::(\\d{2}))?\\s*(am|pm)\\s*-\\s*(\\d{1,2})(?::(\\d{2}))?\\s*(am|pm)/;
  const m = norm.match(re);
  if (!m) return null;
  return {
    start24: to24(parseInt(m[1], 10), parseInt(m[2] || '0', 10), m[3]),
    end24:   to24(parseInt(m[4], 10), parseInt(m[5] || '0', 10), m[6])
  };
}

function to24(h, mins, ampm) {
  let hh = h % 12;
  if (ampm === 'pm') hh += 12;
  return pad(hh) + ':' + pad(mins);
}

function pad(n) { return String(n).padStart(2, '0'); }

function slug(s) {
  return s.toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/** Run this manually from the Apps Script editor to sanity-check output. */
function testBuildSchedule() {
  const result = buildSchedule();
  Logger.log('tracks: ' + result.tracks.length);
  Logger.log('sessions: ' + result.sessions.length);
  Logger.log('sessions with raceId: ' + result.sessions.filter(s => s.raceId).length);
  Logger.log(JSON.stringify(result.tracks, null, 2));
  Logger.log(JSON.stringify(result.sessions.slice(0, 6), null, 2));
}
'''

with open('/tmp/session_race_ids.js') as f:
    map_block = f.read()

with open('tools/io-schedule-apps-script/Code.gs', 'w') as out:
    out.write(HEADER)
    out.write(map_block)
    out.write(FOOTER)

print('Wrote tools/io-schedule-apps-script/Code.gs')
