/**
 * MultiGP IO 2026 Schedule API
 *
 * Deploy:
 *   1. Open the sheet → Extensions → Apps Script
 *   2. Paste this whole file in (replace any default Code.gs content)
 *   3. Save (disk icon)
 *   4. Run testBuildSchedule once → grant permissions when prompted →
 *      check the Execution log for sane output
 *   5. Deploy → New deployment → Type: Web app
 *      • Execute as: Me
 *      • Who has access: Anyone
 *      → Copy the /exec URL — that's your API endpoint
 *
 * Endpoints:
 *   GET <url>             → full payload
 *   GET <url>?day=Friday  → sessions filtered to that day
 *
 * Re-deploy after any code change (Manage deployments → edit → New version).
 * Sheet edits are picked up live, no redeploy needed.
 *
 * raceId mapping:
 *   Each session's `raceId` field is looked up from SESSION_RACE_IDS below.
 *   Sessions without a mapping (or no activity) get raceId: null.
 *   To refresh the map after races change on multigp.com, run the matcher:
 *     python3 match_races.py > session_race_ids.js
 *   then paste the new SESSION_RACE_IDS block in here and redeploy.
 */

const EVENT_CONFIG = {
  name: 'MultiGP International Open 2026',
  venue: 'AMA Grounds, Muncie, Indiana',
  timezone: 'America/Indiana/Indianapolis',
  dates: {
    'Wednesday': '2026-06-10',
    'Thursday':  '2026-06-11',
    'Friday':    '2026-06-12',
    'Saturday':  '2026-06-13',
    'Sunday':    '2026-06-14'
  },
  // Leave null to use the first sheet; set to a name to be explicit
  sheetName: null
};

const DAY_NAMES = ['Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

// ─────────────────────────────────────────────────────────────────────
// Session → multigp.com race ID mapping
// Generated by match_races.py from the live MultiGP chapter race listing.
// Sessions not in this map get raceId: null in the response.
// ─────────────────────────────────────────────────────────────────────

const SESSION_RACE_IDS = {
  // ──────── Wednesday ────────
  'wednesday-1000-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1000-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1000-main_stage'                   : '32075'   , // Team Race Qualifying
  'wednesday-1000-spec'                         : '32099'   , // Open Fly
  'wednesday-1000-tiny_trainier'                : '32118'   , // High Voltage Race
  'wednesday-1000-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1000-world_cup_2'                  : '32110'   , // Lipo Fires Race
  'wednesday-1100-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1100-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1100-main_stage'                   : '32075'   , // Team Race Qualifying
  'wednesday-1100-spec'                         : '32100'   , // Pro Spec Oval
  'wednesday-1100-tiny_trainier'                : '32118'   , // High Voltage Race
  'wednesday-1100-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1100-world_cup_2'                  : '32110'   , // Lipo Fires Race
  'wednesday-1200-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1200-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1200-main_stage'                   : '32075'   , // Team Race Qualifying
  'wednesday-1200-spec'                         : '32100'   , // Pro Spec Oval
  'wednesday-1200-tiny_trainier'                : '32106'   , // Open Fly
  'wednesday-1200-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1200-world_cup_2'                  : '32112'   , // Open Fly
  'wednesday-1300-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1300-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1300-spec'                         : '32100'   , // Pro Spec Oval
  'wednesday-1300-tiny_trainier'                : '32106'   , // Open Fly
  'wednesday-1300-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1300-world_cup_2'                  : '32117'   , // Cracked Props Race
  'wednesday-1400-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1400-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1400-main_stage'                   : '32076'   , // Team Race Final
  'wednesday-1400-spec'                         : '32099'   , // Open Fly
  'wednesday-1400-tiny_trainier'                : '32106'   , // Open Fly
  'wednesday-1400-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1400-world_cup_2'                  : '32117'   , // Cracked Props Race
  'wednesday-1500-all_skills'                   : '32088'   , // Open Fly
  'wednesday-1500-gq_rookie'                    : '32094'   , // Global Qualifier
  'wednesday-1500-main_stage'                   : '32076'   , // Team Race Final
  'wednesday-1500-spec'                         : '32099'   , // Open Fly
  'wednesday-1500-tiny_trainier'                : '32106'   , // Open Fly
  'wednesday-1500-world_cup_1'                  : '32107'   , // World Cup Qualifying
  'wednesday-1500-world_cup_2'                  : '32111'   , // World Cup Qualifying
  'wednesday-1600-all_skills'                   : '32089'   , // Hammers Race
  'wednesday-1600-gq_rookie'                    : '32097'   , // Burnt Motors Race
  'wednesday-1600-main_stage'                   : '32076'   , // Team Race Final
  'wednesday-1600-spec'                         : '32099'   , // Open Fly
  'wednesday-1600-tiny_trainier'                : '32119'   , // Lipo Fires Race
  'wednesday-1600-world_cup_1'                  : '32116'   , // High Voltage Race
  'wednesday-1600-world_cup_2'                  : '32111'   , // World Cup Qualifying
  'wednesday-1700-all_skills'                   : '32089'   , // Hammers Race
  'wednesday-1700-gq_rookie'                    : '32097'   , // Burnt Motors Race
  'wednesday-1700-main_stage'                   : '32076'   , // Team Race Final
  'wednesday-1700-spec'                         : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'wednesday-1700-tiny_trainier'                : '32119'   , // Lipo Fires Race
  'wednesday-1700-world_cup_1'                  : '32116'   , // High Voltage Race
  'wednesday-1700-world_cup_2'                  : '32111'   , // World Cup Qualifying
  'wednesday-1800-main_stage'                   : '32077'   , // Chapter Organizer Qualifying
  'wednesday-1800-spec'                         : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'wednesday-1800-whoopville'                   : '32175'   , // Whoop Qualifying
  'wednesday-1900-main_stage'                   : '32077'   , // Chapter Organizer Qualifying
  'wednesday-1900-spec'                         : '32120'   , // AER Individual & Team Qualifying
  'wednesday-1900-whoopville'                   : '32175'   , // Whoop Qualifying
  'wednesday-2000-main_stage'                   : '32077'   , // Chapter Organizer Groups of 8 Finals
  'wednesday-2000-spec'                         : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'wednesday-2000-whoopville'                   : '32175'   , // Whoop Qualifying
  'wednesday-2100-main_stage'                   : '32077'   , // Chapter Organizer Groups of 8 Finals
  'wednesday-2100-whoopville'                   : '32175'   , // Whoop Qualifying

  // ──────── Thursday ────────
  'thursday-1000-all_skills'                    : '32088'   , // Open Fly
  'thursday-1000-gq_rookie'                     : '32094'   , // Global Qualifer
  'thursday-1000-main_stage'                    : '32079'   , // Pro Spec Qualifying
  'thursday-1000-spec'                          : '32099'   , // Open Fly
  'thursday-1000-tiny_trainier'                 : '32122'   , // Cracked Props Race
  'thursday-1000-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1000-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1100-all_skills'                    : '32088'   , // Open Fly
  'thursday-1100-gq_rookie'                     : '32094'   , // Global Qualifer
  'thursday-1100-main_stage'                    : '32079'   , // Pro Spec Qualifying
  'thursday-1100-spec'                          : '32101'   , // Freedom Spec Qualifying for Main Stage Evening Race
  'thursday-1100-tiny_trainier'                 : '32122'   , // Cracked Props Race
  'thursday-1100-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1100-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1200-all_skills'                    : '32088'   , // Open Fly
  'thursday-1200-gq_rookie'                     : '32094'   , // Global Qualifer
  'thursday-1200-main_stage'                    : '32079'   , // Pro Spec Qualifying
  'thursday-1200-spec'                          : '32101'   , // Freedom Spec Qualifying for Main Stage Evening Race
  'thursday-1200-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1200-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1200-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1300-all_skills'                    : '32088'   , // Open Fly
  'thursday-1300-gq_rookie'                     : '32096'   , // Open Fly
  'thursday-1300-main_stage'                    : '32079'   , // Pro Spec Qualifying
  'thursday-1300-spec'                          : '32101'   , // Freedom Spec Qualifying for Main Stage Evening Race
  'thursday-1300-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1300-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1300-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1400-all_skills'                    : '32090'   , // Lipo Fires Race
  'thursday-1400-gq_rookie'                     : '32096'   , // Open Fly
  'thursday-1400-main_stage'                    : '32080'   , // Hammers Race
  'thursday-1400-spec'                          : '32101'   , // Freedom Spec Qualifying for Main Stage Evening Race
  'thursday-1400-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1400-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1400-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1500-all_skills'                    : '32090'   , // Lipo Fires Race
  'thursday-1500-gq_rookie'                     : '32096'   , // Open Fly
  'thursday-1500-main_stage'                    : '32080'   , // Hammers Race
  'thursday-1500-spec'                          : '32102'   , // Freedom Spec Oval
  'thursday-1500-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1500-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1500-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1600-all_skills'                    : '32088'   , // Open Fly
  'thursday-1600-gq_rookie'                     : '32098'   , // Burnt Motors Oval
  'thursday-1600-main_stage'                    : '32081'   , // Cracked Props Race
  'thursday-1600-spec'                          : '32102'   , // Freedom Spec Oval
  'thursday-1600-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1600-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1600-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1700-all_skills'                    : '32088'   , // Open Fly
  'thursday-1700-gq_rookie'                     : '32098'   , // Burnt Motors Oval
  'thursday-1700-main_stage'                    : '32081'   , // Cracked Props Race
  'thursday-1700-spec'                          : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'thursday-1700-tiny_trainier'                 : '32106'   , // Open Fly
  'thursday-1700-world_cup_1'                   : '32107'   , // World Cup Qualifying
  'thursday-1700-world_cup_2'                   : '32111'   , // World Cup Qualifying
  'thursday-1800-spec'                          : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'thursday-1800-whoopville'                    : '32175'   , // Whoop Qualifying
  'thursday-1800-world_cup_1'                   : '32109'   , // Build N Fly
  'thursday-1900-main_stage'                    : '32082'   , // Freedom Spec Groups of 8
  'thursday-1900-spec'                          : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'thursday-1900-whoopville'                    : '32175'   , // Whoop Qualifying
  'thursday-1900-world_cup_1'                   : '32109'   , // Build N Fly
  'thursday-2000-main_stage'                    : '32082'   , // Freedom Spec Groups of 8
  'thursday-2000-spec'                          : '32120'   , // AER Qualifying (Open for Individuals & Team)
  'thursday-2000-whoopville'                    : '32175'   , // Whoop Qualifying
  'thursday-2000-world_cup_1'                   : '32109'   , // Build N Fly
  'thursday-2100-main_stage'                    : '32170'   , // Pro Spec Groups of 8
  'thursday-2100-spec'                          : '32121'   , // IO Spec Night Race Hosted By 901 FPV
  'thursday-2100-whoopville'                    : '32175'   , // Whoop Qualifying

  // ──────── Friday ────────
  'friday-1000-all_skills'                      : '32088'   , // Open Fly
  'friday-1000-gq_rookie'                       : '32096'   , // Open Fly
  'friday-1000-main_stage'                      : '32083'   , // 40-49 Masters
  'friday-1000-spec'                            : '32104'   , // IO Spec
  'friday-1000-tiny_trainier'                   : '32128'   , // Hammers Race
  'friday-1000-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1000-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1100-all_skills'                      : '32088'   , // Open Fly
  'friday-1100-gq_rookie'                       : '32096'   , // Open Fly
  'friday-1100-main_stage'                      : '32083'   , // 40-49 Masters
  'friday-1100-spec'                            : '32104'   , // IO Spec
  'friday-1100-tiny_trainier'                   : '32128'   , // Hammers Race
  'friday-1100-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1100-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1200-all_skills'                      : '32091'   , // Lipo Fires Race
  'friday-1200-gq_rookie'                       : '32096'   , // Open Fly
  'friday-1200-main_stage'                      : '32083'   , // 40-49 Masters
  'friday-1200-spec'                            : '32104'   , // IO Spec
  'friday-1200-tiny_trainier'                   : '32106'   , // Open Fly
  'friday-1200-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1200-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1300-all_skills'                      : '32091'   , // Lipo Fires Race
  'friday-1300-gq_rookie'                       : '32126'   , // Burn Motors Race
  'friday-1300-main_stage'                      : '32083'   , // 40-49 Masters
  'friday-1300-spec'                            : '32099'   , // Open Fly
  'friday-1300-tiny_trainier'                   : '32106'   , // Open Fly
  'friday-1300-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1300-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1400-all_skills'                      : '32088'   , // Open Fly
  'friday-1400-gq_rookie'                       : '32126'   , // Burn Motors Race
  'friday-1400-main_stage'                      : '32083'   , // 40-49 Masters
  'friday-1400-spec'                            : '32105'   , // IO Spec Oval
  'friday-1400-tiny_trainier'                   : '32106'   , // Open Fly
  'friday-1400-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1400-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1500-all_skills'                      : '32088'   , // Open Fly
  'friday-1500-gq_rookie'                       : '32096'   , // Open Fly
  'friday-1500-spec'                            : '32105'   , // IO Spec Oval
  'friday-1500-tiny_trainier'                   : '32106'   , // Open Fly
  'friday-1500-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1500-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1600-all_skills'                      : '32092'   , // Hammers Race
  'friday-1600-gq_rookie'                       : '32096'   , // Open Fly
  'friday-1600-main_stage'                      : '32084'   , // 50+ Vintage
  'friday-1600-spec'                            : '32105'   , // IO Spec Oval
  'friday-1600-tiny_trainier'                   : '32129'   , // Burnt Motors Race
  'friday-1600-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1600-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1700-all_skills'                      : '32092'   , // Hammers Race
  'friday-1700-gq_rookie'                       : '32127'   , // 2 Pilots 1 quad
  'friday-1700-main_stage'                      : '32084'   , // 50+ Vintage
  'friday-1700-spec'                            : '32123'   , // AER Individual Finals
  'friday-1700-tiny_trainier'                   : '32129'   , // Burnt Motors Race
  'friday-1700-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1700-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1800-gq_rookie'                       : '32127'   , // 2 Pilots 1 quad
  'friday-1800-main_stage'                      : '32084'   , // 50+ Vintage
  'friday-1800-spec'                            : '32123'   , // AER Individual Finals
  'friday-1800-whoopville'                      : '32175'   , // Last Chance Whoop Qualifying
  'friday-1800-world_cup_1'                     : '32107'   , // World Cup Qualifying
  'friday-1800-world_cup_2'                     : '32111'   , // World Cup Qualifying
  'friday-1900-spec'                            : '32124'   , // AER Team Finals
  'friday-1900-whoopville'                      : '32175'   , // Last Chance Whoop Qualifying
  'friday-2000-main_stage'                      : '32085'   , // Ladies and Juniors Race
  'friday-2000-spec'                            : '32124'   , // AER Team Finals
  'friday-2000-whoopville'                      : '32175'   , // Whoop Finals
  'friday-2100-main_stage'                      : null      , // Movie Night After the Racing: "AER Cali Clash 2025 Permiere"
  'friday-2100-spec'                            : '32125'   , // Pro Spec 10 Round Battle Royal by Utah Drone Racing
  'friday-2100-whoopville'                      : '32175'   , // Whoop Finals

  // ──────── Saturday ────────
  'saturday-1000-all_skills'                    : '32088'   , // Open Fly
  'saturday-1000-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1000-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1000-spec'                          : '32103'   , // Hammers Bracket Race
  'saturday-1000-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1000-world_cup_1'                   : '32108'   , // Almost World Cup Finals
  'saturday-1000-world_cup_2'                   : '32112'   , // Open Fly
  'saturday-1100-all_skills'                    : '32088'   , // Open Fly
  'saturday-1100-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1100-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1100-spec'                          : '32103'   , // Hammers Bracket Race
  'saturday-1100-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1100-world_cup_1'                   : '32108'   , // Almost World Cup Finals
  'saturday-1100-world_cup_2'                   : '32112'   , // Open Fly
  'saturday-1200-all_skills'                    : '32088'   , // Open Fly
  'saturday-1200-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1200-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1200-spec'                          : '32103'   , // Hammers Bracket Race
  'saturday-1200-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1200-world_cup_1'                   : '32108'   , // Almost World Cup Finals
  'saturday-1200-world_cup_2'                   : '32112'   , // Open Fly
  'saturday-1300-all_skills'                    : '32093'   , // Burnt Motors Bracket Race
  'saturday-1300-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1300-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1300-spec'                          : '32099'   , // Open Fly
  'saturday-1300-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1300-world_cup_1'                   : '32173'   , // Open Fly
  'saturday-1300-world_cup_2'                   : '32113'   , // Lipo Fires Bracket Race
  'saturday-1400-all_skills'                    : '32093'   , // Burnt Motors Bracket Race
  'saturday-1400-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1400-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1400-spec'                          : '32099'   , // Open Fly
  'saturday-1400-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1400-world_cup_1'                   : '32173'   , // Open Fly
  'saturday-1400-world_cup_2'                   : '32113'   , // Lipo Fires Bracket Race
  'saturday-1500-all_skills'                    : '32093'   , // Burnt Motors Bracket Race
  'saturday-1500-gq_rookie'                     : '32095'   , // Second Global Qualifier
  'saturday-1500-main_stage'                    : '32086'   , // World Cup Practice
  'saturday-1500-spec'                          : '32099'   , // Open Fly
  'saturday-1500-tiny_trainier'                 : '32106'   , // Open Fly
  'saturday-1500-world_cup_1'                   : '32173'   , // Open Fly
  'saturday-1500-world_cup_2'                   : '32113'   , // Lipo Fires Bracket Race
  'saturday-1700-main_stage'                    : null      , // Kung Fu Fightn/ Volunteer Apprication Raffle
  'saturday-1800-main_stage'                    : '32087'   , // World Cup Finals Brackets of 8, 64 pilots
  'saturday-1900-main_stage'                    : '32087'   , // World Cup Finals Brackets of 8, 64 pilots
  'saturday-2000-main_stage'                    : '32087'   , // World Cup Finals Brackets of 8, 64 pilots
  'saturday-2100-main_stage'                    : '32087'   , // World Cup Finals Brackets of 8, 64 pilots

  // ──────── Sunday ────────
  'sunday-1000-gq_rookie'                       : '32095'   , // Second Global Qualifier
  'sunday-1000-main_stage'                      : null      , // World Cup Rain Day
  'sunday-1000-world_cup_1'                     : '32173'   , // Open Fly
  'sunday-1100-gq_rookie'                       : '32095'   , // Second Global Qualifier
  'sunday-1100-main_stage'                      : null      , // World Cup Rain Day
  'sunday-1100-world_cup_1'                     : '32173'   , // Open Fly
  'sunday-1200-gq_rookie'                       : '32095'   , // Second Global Qualifier
  'sunday-1200-main_stage'                      : null      , // World Cup Rain Day
  'sunday-1200-world_cup_1'                     : '32173'   , // Open Fly
  'sunday-1300-gq_rookie'                       : '32095'   , // Second Global Qualifier
  'sunday-1300-main_stage'                      : null      , // World Cup Rain Day
  'sunday-1300-world_cup_1'                     : '32173'   , // Open Fly

};

function doGet(e) {
  try {
    const data = buildSchedule();
    const dayParam = e && e.parameter && e.parameter.day;
    if (dayParam) {
      const wanted = dayParam.toLowerCase();
      data.sessions = data.sessions.filter(s => s.day.toLowerCase() === wanted);
    }
    return jsonResponse(data);
  } catch (err) {
    return jsonResponse({ error: err.message, stack: err.stack });
  }
}

function jsonResponse(obj) {
  return ContentService
    .createTextOutput(JSON.stringify(obj))
    .setMimeType(ContentService.MimeType.JSON);
}

function buildSchedule() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = EVENT_CONFIG.sheetName
    ? ss.getSheetByName(EVENT_CONFIG.sheetName)
    : ss.getSheets()[0];
  const values = sheet.getDataRange().getValues();

  const tracksMap = {};   // trackId -> { id, name, location }
  const sessions = [];

  for (let r = 0; r < values.length; r++) {
    const row = values[r];
    // Day-header row has the day name in column D (index 3)
    const headerCell = String(row[3] || '').trim();
    if (!DAY_NAMES.includes(headerCell)) continue;

    const day  = headerCell;
    const date = EVENT_CONFIG.dates[day];

    const locationRow = values[r + 1] || [];
    const trackRow    = values[r + 2] || [];

    // Build column-index → trackId map for this day
    const dayTracks = {};
    for (let c = 1; c < trackRow.length; c++) {
      const trackName = String(trackRow[c] || '').trim();
      const location  = String(locationRow[c] || '').trim();
      if (!trackName || trackName === 'Track Name') continue;
      const id = slug(trackName);
      dayTracks[c] = id;
      if (!tracksMap[id]) {
        tracksMap[id] = { id: id, name: trackName, location: location };
      }
    }

    // Walk time-slot rows until we hit a blank time cell (end of day block)
    for (let sr = r + 3; sr < values.length; sr++) {
      const slotRow = values[sr];
      const timeText = String(slotRow[0] || '').trim();
      if (!timeText) break;

      const range = parseTimeRange(timeText);
      if (!range) continue;

      for (const colIdx in dayTracks) {
        const c = Number(colIdx);
        const trackId = dayTracks[c];
        const cell = String(slotRow[c] || '').trim();
        if (!cell) continue; // empty cell = no scheduled activity, skip

        const isClosed = cell.toLowerCase() === 'closed';
        const id = `${day.toLowerCase()}-${range.start24.replace(':', '')}-${trackId}`;
        sessions.push({
          id: id,
          day: day,
          date: date,
          startTime: range.start24,
          endTime: range.end24,
          trackId: trackId,
          activity: isClosed ? null : cell,
          status: isClosed ? 'closed' : 'scheduled',
          raceId: SESSION_RACE_IDS[id] || null
        });
      }
    }
  }

  return {
    event: EVENT_CONFIG.name,
    venue: EVENT_CONFIG.venue,
    timezone: EVENT_CONFIG.timezone,
    lastUpdated: new Date().toISOString(),
    tracks: Object.values(tracksMap),
    sessions: sessions
  };
}

/**
 * Handles "8 am - 10 am", "10 am - 11 am", "8 pm -9 pm", "9 pm-10 pm",
 * "8:30 am - 9:00 am", etc. Returns { start24, end24 } or null.
 */
function parseTimeRange(text) {
  const norm = text.toLowerCase().replace(/\s+/g, ' ').trim();
  const re = /(\d{1,2})(?::(\d{2}))?\s*(am|pm)\s*-\s*(\d{1,2})(?::(\d{2}))?\s*(am|pm)/;
  const m = norm.match(re);
  if (!m) return null;
  return {
    start24: to24(parseInt(m[1], 10), parseInt(m[2] || '0', 10), m[3]),
    end24:   to24(parseInt(m[4], 10), parseInt(m[5] || '0', 10), m[6])
  };
}

function to24(h, mins, ampm) {
  let hh = h % 12;
  if (ampm === 'pm') hh += 12;
  return pad(hh) + ':' + pad(mins);
}

function pad(n) { return String(n).padStart(2, '0'); }

function slug(s) {
  return s.toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

/** Run this manually from the Apps Script editor to sanity-check output. */
function testBuildSchedule() {
  const result = buildSchedule();
  Logger.log('tracks: ' + result.tracks.length);
  Logger.log('sessions: ' + result.sessions.length);
  Logger.log('sessions with raceId: ' + result.sessions.filter(s => s.raceId).length);
  Logger.log(JSON.stringify(result.tracks, null, 2));
  Logger.log(JSON.stringify(result.sessions.slice(0, 6), null, 2));
}
