package com.multigp.racesync.domain.model

data class Aircraft(
    val antenna: String,
    val antennaId: Any,
    val backgroundFileName: String,
    val battery: String,
    val dateAdded: String,
    val dateModified: String,
    val description: String,
    val electronicSpeedControllerId: Any,
    val entryCount: Int,
    val flightControllerId: Any,
    val fpvCameraId: Any,
    val fpvCameraLenseId: Any,
    val frameId: Any,
    val id: String,
    val mainImageFileName: String,
    val motorId: Any,
    val name: String,
    val photos: List<Any>,
    val propellerId: Any,
    val propellerSize: String,
    val retired: String,
    val scannableId: String,
    val size: String,
    val type: String,
    val urlName: String,
    val videoReceiverChannels: Any,
    val videoTransmitter: String,
    val videoTransmitterChannels: String,
    val videoTransmitterPower: Any,
    val wingSize: Any
)